name: CSV2Proj
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  copy-CSV:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          id: ${{secrets.APP_ID}}
          private_key: ${{secrets.PRIVATE_KEY}}
          repositories: <target-repo>
      - uses: actions/checkout@v4
