name: CSV2Proj
on:
  push:
    branches: 
      - main
    paths:
      - BOJ_ExpInflRate_down.csv
      - JGB_rates.csv
      - JRB_rates.csv

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_MAIL: yoshihiro.ashihara@gmail.com
  GITHUB_NAME: Ashihara-Y
  REMOTE_REPO_URL: https://github.com/Ashihara-Y/VFMcalcProj.git

jobs:
  copy-CSV:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: check out code of current repo
        uses: actions/checkout@v4
     
      - name: current_datetime
        run: |
          echo "CURRENT_DATETIME"=$(date)>>$GITHUB_ENV
          
      - name: Commit CSV 1
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env: 
          API_TOKEN_GITHUB: ${{ steps.app-token.outputs.token }}
        with:
          source_file: 
            "BOJ_ExpInflRate_down.csv"
          destination_repo: "Ashihara-Y/VFMcalcProj"
          destination_branch: "build"
          user_email: "github-action[bot]@users.noreply.github.com"
          user_name: "github-actions[bot]"
          commit_message: "CSV_1 updated at:{{ env.CURRENT_DATETIME }}"

      - name: Commit CSV 2
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env: 
          API_TOKEN_GITHUB: ${{ steps.app-token.outputs.token }}
        with:
          source_file: 
            "JGB_rates.csv"
          destination_repo: "Ashihara-Y/VFMcalcProj"
          destination_branch: "build"
          user_email: "github-action[bot]@users.noreply.github.com"
          user_name: "github-actions[bot]"
          commit_message: "CSV_2 updated at:{{ env.CURRENT_DATETIME }}"

      - name: Commit CSV 3
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env: 
          API_TOKEN_GITHUB: ${{ steps.app-token.outputs.token }}
        with:
          source_file: 
            "JRB_rates.csv"
          destination_repo: "Ashihara-Y/VFMcalcProj"
          destination_branch: "build"
          user_email: "github-action[bot]@users.noreply.github.com"
          user_name: "github-actions[bot]"
          commit_message: "CSV_3 updated at:{{ env.CURRENT_DATETIME }}"
