name: CSV2Proj
on:
  push:
    branches: ["main"]
    paths:
      - BOJ_ExpInflRate_down.csv
      - JGB_rates.csv
      - JRB_rates.csv

  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_MAIL: 41898282+github-actions[bot]@users.noreply.github.com
  GITHUB_NAME: github-actions[bot]
  REMOTE_REPO_URL: https://github.com/Ashihara-Y/VFMcalcProj.git

jobs:
  copy-CSV:
    runs-on: ubuntu-latest
    steps:
      - name: Commit CSV
        run: |
          echo "CURRENT_DATETIME"=$(date)>>$GITHUB_ENV
          git remote set-url origin ${{ env.REMOTE_REPO_URL }}
          git config --local user.email ${{ env.GITHUB_MAIL }}
          git config --local user.name ${{ env.GITHUB_NAME }}
          git add BOJ_ExpInflRate_down.csv JGB_rates.csv JRB_rates.csv
          git commit -m ":robot: CSV updated at:{{ env.CURRENT_DATETIME }}"
          git push origin build
