# This is a basic workflow to help you get started with Actions

name: sourceToCSV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  schedule:
    - cron: "0 18 * * 4"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Setup python 3.12
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
          cache: 'pip' # caching pip dependencies

      - run: pip install -U pip
      - run: pip install -Ur requirements.txt

      - name: Get Playwright Version For Browser Cache Key
        id: get-playwright-version
        run: |
          echo "playwright-version=$(playwright --version | sed 's/ //g')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore Cache Playwright Browser
        id: restore-cache-playwright-chromium
        uses: actions/cache/restore@v4
        with:
          path: /home/runner/.cache/ms-playwright
          key: playwright-chromium-${{ steps.get-playwright-version.outputs.playwright-version }}

      - name: Install Playwright Browsers
        run: playwright install chromium
        if: ${{ steps.restore-cache-playwright-chromium.outputs.cache-hit != 'true' }}

      - name: Save Cache – Playwright Browser
        uses: actions/cache@v4
        id: save-cache-playwright-chromium
        with:
          path: /home/runner/.cache/ms-playwright
          key: ${{ steps.restore-cache-playwright-chromium.outputs.cache-primary-key }}

      # Runs playwright for getting Chromium, etc
      #- name: Run playwright install
      #  run: playwright install chromium

      # Runs python code for getting JGB rates
      - name: Run jgb_rates
        run: python jgb_rates.py

      # Runs python code for getting JRB rates
      - name: Run jrb_rates
        run: python jrb_rates.py

      # Runs python code for getting BOJ datas
      - name: Run BOJ_ExpInflRate_down
        run: python BOJ_ExpInflRate_down.py

      # Upload artifacts
      #- name: Archive artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    path: |
      #      *.csv
      #      !jgbcm_all.csv
      #    overwrite: true
            
      # Download artifacts
      #- name: Download artifavts
      #  uses: actions/download-artifact@v4
      #  with:
      #    path: artifacts

      # Push uploaded artifacts
      - name: Push uploaded artifacts
        run: |
          date > generated.txt
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add BOJ_ExpInflRate_down.csv JGB_rates.csv JRB_rates.csv generated.txt 
          git commit -m ":robot: generated"
          git push origin main
     
