# This is a basic workflow to help you get started with Actions

name: sourceToCSV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  schedule:
    - cron: "0 18,19 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Setup python 3.12
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      
      - run: pip install -Ur requirements.txt

      # Runs playwright for getting Chromium, etc
      - name: Run playwright install
        run: playwright install

      # Runs python code for getting JGB rates
      - name: Run jgb_rates
        run: python jgb_rates.py

      # Runs python code for getting JRB rates
      - name: Run jrb_rates
        run: python jrb_rates.py

      # Runs python code for getting BOJ datas
      - name: Run BOJ_ExpInflRate_down
        run: python BOJ_ExpInflRate_down.py

     
